- name: Add a new Tenant
  hosts: all
  connection: local
  gather_facts: false
  vars:
    - aci_login: &aci_login
        hostname: "{{ hostname }}"
        use_proxy: "{{ use_proxy }}"
        use_ssl: "{{ use_ssl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
  tasks:
    - name: Add a new tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant }}"
        description: "" 
        state: "{{ state }}"
      delegate_to: localhost