- name: Add a new Tenant
  hosts: all
  connection: local
  gather_facts: false
  vars:
    ansible_connection: local
  tasks:
    - name: Add a new tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        description: "" 
        state: "{{ state }}"
      delegate_to: localhost

