- name: Add a new Tenant
  hosts: all
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.aci
    host_key_checking: false
    validate_certs: false
    use_ssl: false  

  tasks:
    - name: Add a new tenant
      cisco.aci.aci_tenant:
        tenant: "{{ tenant }}"
        description: "" 
        state: "{{ state }}"
      delegate_to: localhost

