- name: Add a new Tenant
  hosts: all
  gather_facts: false

  tasks:
    - name: Add a new tenant
      cisco.aci.aci_tenant:
        validate_certs: false
        tenant: "{{ tenant }}"
        description: "" 
        state: "{{ state }}"
      delegate_to: localhost

