- name: Add a new Tenant
  hosts: all
  gather_facts: false

  tasks:
    - name: Add a new tenant
      cisco.aci.aci_tenant:
        host: "{{ aci_host }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        tenant: "{{ tenant }}"
        description: "" 
        state: "{{ state }}"
        validate_certs: false
      delegate_to: localhost

