---
- name : Application Profile  Provisioning
  gather_facts: false
  hosts: all

  vars:
    aci_login: &aci_login
        hostname: "{{ hostname }}"
        use_proxy: "{{ use_proxy }}"
        use_ssl: "{{ use_ssl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no

  tasks:
    - name: Add a new AP
      cisco.aci.aci_ap:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        description: "{{ ap_description }}"
        state: "{{ ap_status }}"
      delegate_to: localhost

