---
- name : Bridge Domain Provisioning
  gather_facts: false
  hosts: all

  vars:
    aci_login: &aci_login
        hostname: "{{ hostname }}"
        use_proxy: "{{ use_proxy }}"
        use_ssl: "{{ use_ssl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no

  tasks:

    - name: Add Bridge Domain
      cisco.aci.aci_bd:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        bd: "{{ bd_name }}"
        mac_address: "{{ mac if mac is defined and mac !='' else omit }}"
        vrf: "{{ vrf_name }}"
        enable_multicast: "{{ enablePim if enablePim is defined and enablePim != '' else omit }}"
        enable_routing: "{{ unicast_routing if unicast_routing is defined and unicast_routing != '' else omit }}"
        endpoint_move_detect: "{{ endpoint_move_detect_mode if endpoint_move_detect_mode is defined and endpoint_move_detect_mode != '' else omit }}"
        igmp_snoop_policy: "{{ igmp_snoop_policy if igmp_snoop_policy is defined and igmp_snoop_policy != '' else omit }}"
        l2_unknown_unicast: "{{ l2_unknown_unicast if l2_unknown_unicast is defined and l2_unknown_unicast != '' else omit }}"
        l3_unknown_multicast: "{{ l3_unknown_multicast if l3_unknown_multicast is defined and l3_unknown_multicast != '' else omit }}"
        limit_ip_learn: "{{ limit_ip_learning_to_subnet if limit_ip_learning_to_subnet is defined and limit_ip_learning_to_subnet != '' else omit }}"
        multi_dest: "{{ multi_dest_flood if multi_dest_flood is defined  and multi_dest_flood != '' else omit }}"
        name_alias: "{{ name_alias if name_alias is defined  and name_alias != '' else omit }}"
        arp_flooding: "{{ arp_flood if arp_flood is defined and arp_flood != '' else omit }}"
        ip_learning: "{{ endpoint_data_plane_learning if endpoint_data_plane_learning is defined and endpoint_data_plane_learning != '' else omit }}"
        endpoint_retention_policy: "{{ endpoint_retention_policy if endpoint_retention_policy is defined and endpoint_retention_policy != '' else omit }}"
        state: "{{ bd_status }}"
      delegate_to: localhost

