---
- name : End Point Group  Provisioning
  gather_facts: false
  hosts: all

  vars:
    aci_login: &aci_login
        hostname: "{{ hostname }}"
        use_proxy: "{{ use_proxy }}"
        use_ssl: "{{ use_ssl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no

  tasks:

    - name: Add a new EPG
      cisco.aci.aci_epg:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name}}"
        epg: "{{ epg_name }}"
        description: "{{ epg_description if epg_description is defined else omit}}"
        bd: "{{ bd_name }}"
        preferred_group: "{{ preferred_group if preferred_group is defined and preferred_group != '' else omit }}"
        intra_epg_isolation: "{{ intra_epg_isolation if intra_epg_isolation is defined and intra_epg_isolation != '' else omit }}"
        name_alias: "{{ name_alias if name_alias is defined and name_alias != '' else omit }}"
        priority: "{{ qos_class if qos_class is defined and qos_class != '' else omit }}"
        state: "{{ epg_status }}"
      delegate_to: localhost

