- name: Galaxy Requirements
  hosts: localhost 
  tasks: Fetch galaxy 
    ansible.builtin.command:
      cmd: "ansible-galaxy collection install cisco.ios"
- name: Config Test
  hosts: all
  tasks:
    - name: Config Test
      cisco.ios.ios_config:
          commands:
            - interface loopback20
            - description automated
