- name: Config Test
  hosts: all
  gather_facts: false
  vars: # for execution environment
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos
  tasks:
    - name: Config Test
      cisco.nxos.nxos_config:
          lines:
            - interface loopback20
            - description automated
