- name: Hello World Sample
  hosts: all
  tasks:
    - name: Config Test
      cisco.ios.ios_config:
          commands:
            - interface loopback20
            - description automated
