- name: Config Test
  hosts: all
  gather_facts: false
  tasks:
    - name: Config Test
      cisco.nxos.nxos_config:
          lines:
            - interface loopback20
            - description automated
